version: "3.7"
services:
  php:
    build:
      args:
        version: ${PHP_TAG}
      context: ./
      dockerfile: ./docker-compose/php/Dockerfile
    container_name: "${PROJECT_NAME}-app"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - proxy
  mariadb:
    image: mariadb/server:${MARIADB_TAG}
    container_name: "${PROJECT_NAME}-db"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - proxy
  nginx:
    build:
      args:
        version: ${NGINX_TAG}
      context: .
      dockerfile: ./docker-compose/nginx/Dockerfile
    container_name: "${PROJECT_NAME}-nginx"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${traefik}-x.rule=Host(`${BASE_URL}`)
      - traefik.http.routers.${traefik}-x.tls=true
      - traefik.http.routers.${traefik}-x.tls.certresolver=le
      - traefik.http.routers.${traefik}-x.entrypoints=websecure
      - traefik.http.middlewares.${traefik}-x-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.${traefik}-x-web.middlewares=${traefik}-x-redirect-web-secure
      - traefik.http.routers.${traefik}-x-web.rule=Host(`${BASE_URL}`)
      - traefik.http.routers.${traefik}-x-web.entrypoints=web
  composer:
    build:
      context: .
      dockerfile: ./docker-compose/composer/Dockerfile
    container_name: "${PROJECT_NAME}-composer"
    environment:
      COMPOSER_AUTH: '{"github-oauth":{"github.com":"4b36ae8ff955b4f5845972341e0cd9acb45d5b26"}}'
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - proxy
    entrypoint: ['composer', '--ignore-platform-reqs']
  artisan:
    build:
      args:
        version: ${PHP_TAG}
      context: .
      dockerfile: ./docker-compose/php/Dockerfile
    container_name: "${PROJECT_NAME}-artisan"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - proxy
  redis:
    image: redis:${REDIS_TAG}
    container_name: "${PROJECT_NAME}-redis"
    restart: unless-stopped
    networks:
      - proxy
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}-phpMyadmin"
    environment:
      PMA_HOST: ${DB_HOST}
      UPLOAD_LIMIT: 1G
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${traefik}-pma.rule=Host(`pma.${BASE_URL}`)
      - traefik.http.routers.${traefik}-pma.tls=true
      - traefik.http.routers.${traefik}-pma.tls.certresolver=le
      - traefik.http.routers.${traefik}-pma.entrypoints=websecure
      - traefik.http.middlewares.${traefik}-pma-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.${traefik}-pma-web.middlewares=${traefik}-pma-redirect-web-secure
      - traefik.http.routers.${traefik}-pma-web.rule=Host(`pma.${BASE_URL}`)
      - traefik.http.routers.${traefik}-pma-web.entrypoints=web
networks:
  proxy:
    external:
      name: global_network
volumes:
  mysql:
